baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Home'
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "aurora."
author = "roraosu"
description = "Scanlator, Gamer, Creator"
profilePicture = "images/profile.jpg"
hidesidebar = true
customCss = ["css/list-title.css"]
contactFormAction = "https://formspree.io/f/xknapgob"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "mailto:chompajamas@gmail.com"

[[params.socialIcons]]
icon = "fab fa-discord"
title = "Discord"
url = "https://dsc.gg/evescans/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/auroraongithub"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/twit_aurora"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
  
  [[menu.main]]
  name = "Portfolios"
  weight = 300
  identifier = "portfolios"
  
  [[menu.main]]
  name = "My Portfolio"
  weight = 310
  identifier = "portfolio"
  url = "/portfolio/"
  parent = "portfolios"
  
  [[menu.main]]
  name = "Milestones"
  weight = 320
  identifier = "milestones"
  url = "/milestones/"
  parent = "portfolios"

  [[menu.main]]
  name = "Stories"
  weight = 400
  identifier = "stories"
  url = "/stories/"

  [[menu.main]]
  name = "Blogs"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "Modding"
  weight = 600
  identifier = "modding"
  url = "/modding/"

    [[menu.main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "https://nijika.de/"
